-- Your existing table structure (already created)
-- create table public.rts_patriot (
--   id bigint generated by default as identity not null,
--   created_at timestamp with time zone not null default now(),
--   bib text null default ''::text,
--   name text null default ''::text,
--   gender text null default 'male'::text,
--   category text null default 'umum'::text,
--   blood_type text null default ''::text,
--   cp0 text null default ''::text,
--   cp1 text null default ''::text,
--   cp2 text null default ''::text,
--   cp3 text null default ''::text,
--   cp4 text null default ''::text,
--   is_active boolean null default true,
--   is_dnf boolean not null default false,
--   is_dns boolean null default false,
--   tag text null default ''::text,
--   cp5 text null default ''::text,
--   cp6 text null default ''::text,
--   cp7 text null default ''::text,
--   cp8 text null default ''::text,
--   cp9 text null default ''::text,
--   constraint rts_patriot_pkey primary key (id)
-- ) TABLESPACE pg_default;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_rts_patriot_gender ON rts_patriot(gender);
CREATE INDEX IF NOT EXISTS idx_rts_patriot_category ON rts_patriot(category);
CREATE INDEX IF NOT EXISTS idx_rts_patriot_bib ON rts_patriot(bib);
CREATE INDEX IF NOT EXISTS idx_rts_patriot_is_active ON rts_patriot(is_active);
CREATE INDEX IF NOT EXISTS idx_rts_patriot_cp9 ON rts_patriot(cp9);

-- Enable Row Level Security (RLS)
ALTER TABLE rts_patriot ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Allow public read access" ON rts_patriot
  FOR SELECT USING (true);

-- Insert sample data for testing
INSERT INTO rts_patriot (bib, name, gender, category, blood_type, cp0, cp9, is_active, is_dnf, is_dns, tag) VALUES
-- 10K UMUM
('001', 'John Doe', 'male', '10K UMUM', 'O+', '08:00:00', '10:30:00', true, false, false, ''),
('002', 'Jane Smith', 'female', '10K UMUM', 'A+', '08:00:00', '10:45:00', true, false, false, ''),
('003', 'Mike Johnson', 'male', '10K UMUM', 'B+', '08:00:00', '11:00:00', true, false, false, ''),
-- 10K PELAJAR
('004', 'Sarah Wilson', 'female', '10K PELAJAR', 'AB+', '08:00:00', '11:15:00', true, false, false, ''),
('005', 'David Brown', 'male', '10K PELAJAR', 'O-', '08:00:00', '11:30:00', true, false, false, ''),
('006', 'Lisa Davis', 'female', '10K PELAJAR', 'A-', '08:00:00', '11:45:00', true, false, false, ''),
-- 10K MASTER
('007', 'Tom Miller', 'male', '10K MASTER', 'B-', '08:00:00', '12:00:00', true, false, false, ''),
('008', 'Emma Garcia', 'female', '10K MASTER', 'AB-', '08:00:00', '12:15:00', true, false, false, ''),
-- 5K UMUM
('009', 'Chris Rodriguez', 'male', '5K UMUM', 'O+', '08:00:00', '09:30:00', true, false, false, ''),
('010', 'Anna Martinez', 'female', '5K UMUM', 'A+', '08:00:00', '09:45:00', true, false, false, ''),
-- 5K PELAJAR
('011', 'Budi Santoso', 'male', '5K PELAJAR', 'B+', '08:00:00', '10:00:00', true, false, false, ''),
('012', 'Siti Rahayu', 'female', '5K PELAJAR', 'AB+', '08:00:00', '10:15:00', true, false, false, ''),
-- 5K DISABILITAS
('013', 'Ahmad Wijaya', 'male', '5K DISABILITAS', 'O-', '08:00:00', '10:30:00', true, false, false, ''),
('014', 'Maya Sari', 'female', '5K DISABILITAS', 'A-', '08:00:00', '10:45:00', true, false, false, ''),
-- DNF examples
('015', 'DNF Runner', 'male', '10K UMUM', 'B-', '08:00:00', '', true, true, false, ''),
('016', 'DNS Runner', 'female', '5K UMUM', 'AB-', '08:00:00', '', true, false, true, '');
